### ISSUE TITLE
Tried To Read From Address Zero when dropping a non-empty logistics bag.

### ISSUE THREAD

**Issue by Mohl97** [Deadondev/Cozis-Offworld-Wares#4]
`VM execution aborted: tried to read from address zero.
Called from HD_LogiBag.CreateTossable at C:/Users/Alex/Documents/GitHub/Cozis-Offworld-Wares/:zscript/items/logibag.zsc, line 148
Called from Actor.DropInventory at gzdoom.pk3:zscript/actors/inventory_util.zs, line 292`

Haven't checked what specifically might be going wrong yet, but then again I don't know shit about backpack code so I wouldn't be able to figure it out anyway. Dropping empty logistics bags works fine though, at least.

**Comment by tedthepraimortis** [comment]
I cannot replicate this, are you running on low encumbrance mode and what specifically did you have in the backpack?
Line 148 is double UnitBulk = HDPickup(getdefaultbytype(SelItem.ItemClass)).bulk * hdmath.getencumbrancemult(); so it'd likely be something relating to bulk, though seemingly regardless of what I did I cannot replicate this.

**Comment by Mohl97** [comment]
I was testing on 1.0 encumbrance, but I know the issue more now: It's something to do with having multiple logistics bags that contain a reloader. If you have one bag that already has a reloader in it, then pick up another bag, everything works fine. If you take that reloader out, and put it back in however, I can only assume the bags try to split the reloader's weight between the two bags, and will crash your game unless you take the reloader out before dropping any bags.

or for more concise instructions on replicating: pick up two logistics bags, pick up a reloader, put it in the bags, drop a bag.

**Comment by tedthepraimortis** [comment]
Technically fixed by the above commit, though it just removes the reloaders from the backpack now that I know it's them. I'm going to keep this open as I don't exactly know what's causing it to VM abort and I'll keep looking over it.

**Comment by tedthepraimortis** [comment]
As nothing else seems to have come from this, I'll close it.
