### ISSUE TITLE
Tried to Read From Address Zero when loading a map

### ISSUE THREAD

**Issue by Mohl97** [Deadondev/Cozis-Offworld-Wares#8]
![image](https://user-images.githubusercontent.com/13591160/215040603-7420f7bd-082e-4ea1-9645-a0c45aff1c00.png)
As far as I can guess, the event handler is trying to spawn stuff that doesn't exist anymore, causing an error. It's not as likely to happen on a map like the firing range due to the amount of stuff in that, but on a proper map it's practically guaranteed to try and spawn a logistics bag and fail.

**Comment by tedthepraimortis** [comment]
Technically fixed in most recent commit though it's incredibly lazy. Will be fixed when I feel like making a offworld-wares item pack to separate requirements of UaS and such to either that or a separate mod.
